name: Deploy Frontend

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalacion Limpia 📥
        # npm ci es mejor que install para servidores, es mas estricto y limpio
        run: npm ci || npm install

      - name: Build Forzado 🏗️
        run: |
          # Le damos permisos de ejecucion manualmente a la carpeta de binarios
          chmod -R +x node_modules/.bin
          # Ejecutamos el build usando npx para asegurar que encuentre Vite
          npx vite build

      - name: Upload Artifact 📤
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4