name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Se activa al subir cambios a la rama main

permissions:
  contents: write  # Permiso para crear y escribir en la rama gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Evita avisos de deprecación

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Configurar Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar y Construir 🏗️
        run: |
          npm install
          # npx evita el error de "Permission denied" al ejecutar vite directamente
          npx vite build

      - name: Desplegar a GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist 
          branch: gh-pages 